version: "3"
services: 
    app2:
        container_name: app2
        build:  .
        command: node index.js
        ports:
            - "3000:3000"
        depends_on:  
            - "mongo"
    mongo:
        container_name: mongo
        image: mongo
        ports:
            - "27017:27017" 
